[WIP] new version of train and test
MLSysOps/TorchScene pull request #8
Opened 2022-06-19 15:46 UTC by STALLAAAA

1. deprecate old training scripts and utils[Done]
2. replace test with infer[Done]
3. add tensorboard plugin[TODO]

2022-06-26 08:25 UTC, HuaizhengZhang requested changes
Kindly please understand why I build utils to manage functions before mimic styles from torch examples which are must be in the same file.

Logging info should be kept as hyper, env, etc also important

2022-06-26 08:25 UTC, HuaizhengZhang commented on tools/train.py
> -    mkdir(cfgs['weight_dir'])
where could i get the saved log information?

2022-06-26 08:25 UTC, HuaizhengZhang commented on tools/train.py
> +def collect_env_info():
I prefer these functions should be in the utils. 


 Before change this, try to understand why I move these functions to different files which is different from the torch examples.


We build tools while torch examples show how to use them. That's why they put all together but this is not what we want.

2022-06-26 08:25 UTC, HuaizhengZhang commented on tools/train.py
> -    mkdir(cfgs['weight_dir'])
env? hyperparamters?

I understand that loss is stored in tensorbord.

2022-07-09 11:24 UTC, STALLAAAA commented on tools/train.py
> -    mkdir(cfgs['weight_dir'])
log info is saved at `/logs` as `conf/train.yaml` 'hydra' indicated.

2022-07-09 11:24 UTC, STALLAAAA commented on tools/train.py
> +def collect_env_info():
OK, I will move them to utils.

2022-07-09 11:25 UTC, STALLAAAA commented
@HuaizhengZhang Changes have been made, have a check plz.

2022-07-19 06:54 UTC, HuaizhengZhang approved these changes

2022-07-19 06:54 UTC, merged